image:
  file: .gitpod.Dockerfile

github:
  prebuilds:    
    master: true    
    branches: true    
    pullRequests: true    
    pullRequestsFromForks: false    
    addCheck: true    
    addComment: false    
    addBadge: false

tasks:      
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      # Initialize NPM for starting containers
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i      
      cd $THEIA_WORKSPACE_ROOT
  
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      gp env GITPOD_IP=$(curl ifconfig.me)
      source  "$THEIA_WORKSPACE_ROOT/backend-flask/bin/rds-update-sg-rule"
  #- name: Docker Login
  #  command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

# Add VSCode Extensions
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - ms-python.python
    - hashicorp.terraform
    - redhat.ansible
    - redhat.vscode-yaml
    - amazonwebservices.aws-toolkit-vscode

# Unlock Gitpod Ports
ports:
  - name: frontend
    port: 3000
    onOpen: ignore
    visibility: public
  - name: backend
    port: 4567
    onOpen: ignore
    visibility: public
  - name: xray-daemon
    port: 2000
    onOpen: ignore
    visibility: public